name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build jars
      id: build-jars
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Build jars
        setup-command: ''
        command: gradle jar
        timeout: 10
        max-score: 0
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        BUILD-JARS_RESULTS: "${{steps.build-jars.outputs.result}}"
      with:
        runners: build-jars
